# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AxxessCodingChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AxxessCodingChallenge
  pod 'Alamofire'
  pod 'SnapKit', '~> 4.0'
end
